### ISSUE TITLE
执行器添加错误处理的实现

### ISSUE THREAD

**Issue by livstyle** [os2edu/rust-shell-clone-project#7]
![image](https://user-images.githubusercontent.com/77309755/159842276-587b3da3-9573-4c4c-9076-a7d5740c8856.png)

在core crate中 Command trait是否需要加一个Result统一一下错误处理

**Comment by YYMMYB** [comment]
是应该加个错处处理, 错误统一都在 frame 的 main 函数中打印.

在 [5c8cfb7](https://github.com/os2edu/rust-shell-clone-project/commit/5c8cfb7c4bffde242490e321fe347070baee3182) 中, 我在 core 里加了个 Result 类型, 是 anyhow::Result 的别名.
我觉得这个类型可以作为整个库的错误返回类型? 所以我把 input 的错误类型删了, 也换成了这个类型(虽然都是 anyhow::Result).

这样做合适吗? 还是 frame 和 命令的 错误类型应当分开?
直接用 anyhow 好吗? 还是应当定义一个自己的Error枚举类型?
